import { motion } from 'framer-motion';
import { BarChart3, Download } from 'lucide-react';
import { useComparison } from '../hooks/useComparison';
import { ImageAnalysis } from '../types';
import { getSeverityColor } from '../utils';

interface ComparisonDashboardProps {
  images: ImageAnalysis[];
}

export function ComparisonDashboard({ images }: ComparisonDashboardProps) {
  const {
    analyzedImages,
    shouldShowComparison,
    defectFrequency,
    totalCostRange,
    mostUrgentIssue,
  } = useComparison(images);

  if (!shouldShowComparison) return null;

  const downloadPortfolioReport = () => {
    const urgentIssueText = mostUrgentIssue
      ? `MOST URGENT ISSUE:\n${mostUrgentIssue.defect} appears in ${mostUrgentIssue.count} ${
          mostUrgentIssue.count === 1 ? 'property' : 'properties'
        }`
      : '';

    const text = `
SURVEYAI — PORTFOLIO ANALYSIS REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Properties Analyzed: ${analyzedImages.length}
Date: ${new Date().toLocaleDateString('en-GB')}

PORTFOLIO SUMMARY:
${analyzedImages
  .map(
    (img) =>
      `${img.reference} — ${img.report?.severity.toUpperCase()} (${img.report?.severity_score}/100)`
  )
  .join('\n')}

TOTAL ESTIMATED REPAIR COSTS:
  Conservative: £${totalCostRange.low.toLocaleString()}
  Mid-range:    £${totalCostRange.mid.toLocaleString()}
  Full scope:   £${totalCostRange.high.toLocaleString()}

${urgentIssueText}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by SurveyAI · Taurgo × Cardiff University Hackathon 2026
    `.trim();

    navigator.clipboard.writeText(text);
    alert('Portfolio report copied to clipboard!');
  };

  return (
    <section id="comparison" className="py-16 px-4">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 glass-panel-sm px-4 py-2 mb-4">
            <BarChart3 size={20} style={{ color: 'var(--accent-gold)' }} />
            <span className="text-sm font-semibold uppercase tracking-wider" style={{ color: 'var(--accent-gold)' }}>
              The Differentiator
            </span>
          </div>
          <h2
            className="text-3xl md:text-4xl font-bold mb-4"
            style={{ color: 'var(--accent-primary)' }}
          >
            Portfolio Defect Intelligence
          </h2>
          <p style={{ color: 'var(--text-secondary)' }}>
            Comparing {analyzedImages.length} surveyed properties
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          {analyzedImages.map((image, index) => (
            <motion.div
              key={image.id}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className="neu-card p-4"
            >
              <div className="relative">
                <img
                  src={image.dataUrl}
                  alt="Property"
                  className="w-full h-48 object-cover rounded-lg mb-3"
                />
                {image.report && (
                  <div
                    className="absolute top-2 right-2 px-3 py-1 rounded-full text-xs font-bold text-white"
                    style={{ background: getSeverityColor(image.report.severity) }}
                  >
                    {image.report.severity.toUpperCase()}
                  </div>
                )}
              </div>
              <div className="mono text-xs mb-2" style={{ color: 'var(--accent-secondary)' }}>
                {image.reference}
              </div>
              {image.report && (
                <div className="flex flex-wrap gap-1">
                  {image.report.defect_categories.slice(0, 3).map((defect, i) => (
                    <span
                      key={i}
                      className="text-xs px-2 py-1 rounded"
                      style={{ background: 'var(--glass-bg)', color: 'var(--text-secondary)' }}
                    >
                      {defect.icon} {defect.name}
                    </span>
                  ))}
                </div>
              )}
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="glass-panel p-8 mb-8"
        >
          <h3
            className="text-xl font-bold mb-6"
            style={{ color: 'var(--accent-primary)' }}
          >
            Severity Timeline
          </h3>
          <div className="space-y-4">
            {analyzedImages.map((image, index) => {
              if (!image.report) return null;
              const percentage = image.report.severity_score;
              return (
                <motion.div
                  key={image.id}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                >
                  <div className="flex items-center gap-3 mb-2">
                    <span className="mono text-xs w-28" style={{ color: 'var(--text-secondary)' }}>
                      {image.reference}
                    </span>
                    <div className="flex-1 h-8 rounded-lg overflow-hidden" style={{ background: 'var(--glass-bg)' }}>
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${percentage}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 1, delay: index * 0.1 }}
                        className="h-full flex items-center justify-end px-3"
                        style={{ background: getSeverityColor(image.report.severity) }}
                      >
                        <span className="text-xs font-bold text-white">
                          {image.report.severity.toUpperCase()}
                        </span>
                      </motion.div>
                    </div>
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="glass-panel p-8 mb-8"
        >
          <h3
            className="text-xl font-bold mb-6"
            style={{ color: 'var(--accent-primary)' }}
          >
            Defect Frequency Heatmap
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr>
                  <th className="text-left py-2 px-3" style={{ color: 'var(--text-secondary)' }}>
                    Defect Type
                  </th>
                  {analyzedImages.map((image) => (
                    <th
                      key={image.id}
                      className="text-center py-2 px-3 mono text-xs"
                      style={{ color: 'var(--text-secondary)' }}
                    >
                      {image.reference.split('-')[2]}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {Object.entries(defectFrequency).map(([defect, imageMap], index) => (
                  <motion.tr
                    key={defect}
                    initial={{ opacity: 0, x: -10 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <td
                      className="py-2 px-3 font-medium"
                      style={{ color: 'var(--text-primary)' }}
                    >
                      {defect}
                    </td>
                    {analyzedImages.map((image) => (
                      <td key={image.id} className="text-center py-2 px-3">
                        {imageMap[image.id] ? (
                          <div
                            className="inline-flex items-center justify-center w-8 h-8 rounded-full"
                            style={{
                              background: 'var(--accent-secondary)',
                              color: 'white',
                              fontSize: '10px',
                            }}
                            title={`${imageMap[image.id]}% confidence`}
                          >
                            {Math.round(imageMap[image.id])}
                          </div>
                        ) : (
                          <div
                            className="inline-flex items-center justify-center w-8 h-8 rounded-full"
                            style={{ background: 'var(--glass-bg)' }}
                          >
                            <span style={{ color: 'var(--text-muted)' }}>○</span>
                          </div>
                        )}
                      </td>
                    ))}
                  </motion.tr>
                ))}
              </tbody>
            </table>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="glass-panel p-8 mb-8"
        >
          <h3
            className="text-xl font-bold mb-4"
            style={{ color: 'var(--accent-primary)' }}
          >
            Priority Action Summary
          </h3>
          {mostUrgentIssue && (
            <p className="text-lg leading-relaxed mb-4" style={{ color: 'var(--text-primary)' }}>
              Across your portfolio, the most urgent issue is{' '}
              <strong style={{ color: 'var(--severity-critical)' }}>
                {mostUrgentIssue.defect}
              </strong>{' '}
              appearing in{' '}
              <strong>{mostUrgentIssue.count}</strong>{' '}
              {mostUrgentIssue.count === 1 ? 'property' : 'properties'}.
            </p>
          )}
          <p className="text-lg leading-relaxed" style={{ color: 'var(--text-primary)' }}>
            Estimated combined repair budget:{' '}
            <strong style={{ color: 'var(--accent-gold)' }}>
              £{totalCostRange.low.toLocaleString()} – £{totalCostRange.high.toLocaleString()}
            </strong>
          </p>
        </motion.div>

        <div className="text-center">
          <button
            onClick={downloadPortfolioReport}
            className="neu-button px-8 py-4 text-white font-semibold inline-flex items-center gap-3"
            style={{ background: 'var(--accent-primary)' }}
          >
            <Download size={20} />
            Download Full Portfolio Report
          </button>
        </div>
      </div>
    </section>
  );
}
