import jsPDF from 'jspdf';

// ─── CONSTANTS ───────────────────────────────────────────────────────────────
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 14;
const CONTENT_W = PAGE_W - MARGIN * 2;

const NAVY = [26, 58, 107] as const;
const GOLD = [201, 148, 58] as const;
const LIGHT_GREY = [248, 249, 250] as const;
const BORDER = [229, 231, 235] as const;
const TEXT_PRIMARY = [26, 32, 53] as const;
const TEXT_SECONDARY = [74, 85, 120] as const;
const TEXT_MUTED = [156, 163, 175] as const;

const SEVERITY_RGB: Record<string, [number, number, number]> = {
  Monitor:  [37,  99,  235],
  Low:      [22,  163, 74],
  Medium:   [217, 119, 6],
  High:     [234, 88,  12],
  Critical: [220, 38,  38],
};

// ─── TYPES ───────────────────────────────────────────────────────────────────
interface DefectCategory {
  icon?: string;
  name: string;
  taxonomy_short?: string;
  taxonomy_long?: string;
  confidence: number;
  severity: string;
}

interface Recommendation {
  priority: string;
  action: string;
  specialist: string;
  timeframe: string;
}

interface Citation {
  reference: string;
  title: string;
  relevance: string;
}

interface Report {
  ref: string;
  date: string;
  previewUrl?: string;
  severity: string;
  severityScore: number;
  urgency: string;
  defectCategories: DefectCategory[];
  surveyDescription: string;
  riskMatrix?: { likelihood: string; impact: string };
  costEstimate?: { low: number; mid: number; high: number };
  recommendations: Recommendation[];
  citations?: Citation[];
  analysisLimitations?: string;
}

interface SurveyContext {
  propertyType?: string;
  buildingAge?: string;
  locationType?: string;
  reportPurpose?: string;
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function clean(text: string): string {
  // Remove all non-latin printable characters jsPDF Helvetica cannot render
  return text
    .replace(/[^\x20-\x7E\xA0-\xFF]/g, '')
    .replace(/£/g, 'GBP')
    .trim();
}

function setColor(pdf: jsPDF, rgb: readonly [number, number, number], type: 'fill' | 'text' | 'draw') {
  if (type === 'fill') pdf.setFillColor(rgb[0], rgb[1], rgb[2]);
  else if (type === 'text') pdf.setTextColor(rgb[0], rgb[1], rgb[2]);
  else pdf.setDrawColor(rgb[0], rgb[1], rgb[2]);
}

function sevRgb(severity: string): [number, number, number] {
  return SEVERITY_RGB[severity] ?? [26, 58, 107];
}

function totalLow(reports: Report[]): number {
  return reports.reduce((s, r) => s + (r.costEstimate?.low ?? 0), 0);
}

function totalHigh(reports: Report[]): number {
  return reports.reduce((s, r) => s + (r.costEstimate?.high ?? 0), 0);
}

function highestSeverity(reports: Report[]): string {
  for (const s of ['Critical', 'High', 'Medium', 'Low', 'Monitor']) {
    if (reports.some(r => r.severity === s)) return s;
  }
  return 'Monitor';
}

function hline(pdf: jsPDF, x1: number, y: number, x2: number, color: readonly [number,number,number] = BORDER, width = 0.25) {
  setColor(pdf, color, 'draw');
  pdf.setLineWidth(width);
  pdf.line(x1, y, x2, y);
}

function filledRect(pdf: jsPDF, x: number, y: number, w: number, h: number, fill: readonly [number,number,number], border?: readonly [number,number,number]) {
  setColor(pdf, fill, 'fill');
  pdf.rect(x, y, w, h, border ? 'FD' : 'F');
  if (border) {
    setColor(pdf, border, 'draw');
    pdf.setLineWidth(0.25);
    pdf.rect(x, y, w, h, 'S');
  }
}

function outlineRect(pdf: jsPDF, x: number, y: number, w: number, h: number, border: readonly [number,number,number] = BORDER) {
  setColor(pdf, border, 'draw');
  pdf.setLineWidth(0.25);
  pdf.rect(x, y, w, h, 'S');
}

function sectionLabel(pdf: jsPDF, label: string, x: number, y: number, lineW: number): number {
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  setColor(pdf, NAVY, 'text');
  pdf.text(label.toUpperCase(), x, y);
  hline(pdf, x, y + 1.5, x + lineW, NAVY, 0.4);
  return y + 5.5;
}

// ─── SHARED HEADER / FOOTER ──────────────────────────────────────────────────
function pageHeader(pdf: jsPDF) {
  filledRect(pdf, 0, 0, PAGE_W, 9, NAVY);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  pdf.text('SurveyAI', MARGIN, 6);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.text('Taurgo x Cardiff University  |  AI Hackathon 2026', PAGE_W / 2, 6, { align: 'center' });
}

function pageFooter(pdf: jsPDF) {
  hline(pdf, MARGIN, PAGE_H - 10, PAGE_W - MARGIN);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text(
    'Generated by SurveyAI  |  Powered by Claude AI (Anthropic) & Nova Pro (Amazon)  |  For informational purposes only. Always consult a qualified RICS Chartered Surveyor.',
    PAGE_W / 2, PAGE_H - 6.5,
    { align: 'center', maxWidth: CONTENT_W }
  );
}

// ─── PAGE 1: COVER ───────────────────────────────────────────────────────────
function coverPage(pdf: jsPDF, context: SurveyContext, reports: Report[], date: string) {
  pageHeader(pdf);
  pageFooter(pdf);

  let y = 20;

  // Logo / title block
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(28);
  setColor(pdf, NAVY, 'text');
  pdf.text('SurveyAI', PAGE_W / 2, y, { align: 'center' });
  y += 8;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  setColor(pdf, TEXT_SECONDARY, 'text');
  pdf.text('Property Defect Analysis Report', PAGE_W / 2, y, { align: 'center' });
  y += 5;

  pdf.setFontSize(7.5);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text('Generated: ' + date, PAGE_W / 2, y, { align: 'center' });
  y += 8;

  // Gold divider
  setColor(pdf, GOLD, 'draw');
  pdf.setLineWidth(0.8);
  pdf.line(MARGIN + 25, y, PAGE_W - MARGIN - 25, y);
  y += 8;

  // ── Survey Context ──
  y = sectionLabel(pdf, 'Survey Context', MARGIN, y, CONTENT_W);

  const ctxFields = [
    ['Property Type', context.propertyType ?? 'Not specified'],
    ['Building Age',  context.buildingAge  ?? 'Not specified'],
    ['Location Type', context.locationType ?? 'Not specified'],
    ['Report Purpose',context.reportPurpose?? 'Not specified'],
  ];
  const cW = (CONTENT_W - 4) / 2;
  ctxFields.forEach(([label, value], i) => {
    const cx = MARGIN + (i % 2) * (cW + 4);
    const cy = y + Math.floor(i / 2) * 16;
    filledRect(pdf, cx, cy, cW, 13, LIGHT_GREY, BORDER);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    setColor(pdf, TEXT_MUTED, 'text');
    pdf.text(label.toUpperCase(), cx + 3, cy + 5);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8.5);
    setColor(pdf, NAVY, 'text');
    pdf.text(clean(value), cx + 3, cy + 10.5);
  });
  y += 36;

  // ── Portfolio Summary ──
  y = sectionLabel(pdf, 'Portfolio Summary', MARGIN, y, CONTENT_W);

  const sW = (CONTENT_W - 4) / 3;
  const hs = highestSeverity(reports);
  const stats = [
    { label: 'Properties Analysed', value: String(reports.length), color: NAVY as readonly [number,number,number] },
    { label: 'Highest Severity',    value: hs,                      color: sevRgb(hs) as readonly [number,number,number] },
    { label: 'Total Repair Budget', value: `GBP ${totalLow(reports).toLocaleString()} - GBP ${totalHigh(reports).toLocaleString()}`, color: NAVY as readonly [number,number,number] },
  ];
  stats.forEach((s, i) => {
    const sx = MARGIN + i * (sW + 2);
    filledRect(pdf, sx, y, sW, 18, LIGHT_GREY, BORDER);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6);
    setColor(pdf, TEXT_MUTED, 'text');
    pdf.text(s.label.toUpperCase(), sx + 3, y + 5);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(9);
    setColor(pdf, s.color, 'text');
    pdf.text(clean(s.value), sx + 3, y + 13.5);
  });
  y += 22;

  // ── Reports list ──
  y = sectionLabel(pdf, 'Reports Included', MARGIN, y, CONTENT_W);

  reports.forEach((r, i) => {
    const bg = i % 2 === 0 ? LIGHT_GREY : ([255,255,255] as [number,number,number]);
    filledRect(pdf, MARGIN, y, CONTENT_W, 10, bg);
    outlineRect(pdf, MARGIN, y, CONTENT_W, 10);

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7.5);
    setColor(pdf, NAVY, 'text');
    pdf.text(r.ref, MARGIN + 3, y + 6.5);

    const sc = sevRgb(r.severity);
    pdf.setFontSize(7);
    setColor(pdf, sc, 'text');
    pdf.text(r.severity.toUpperCase(), MARGIN + 46, y + 6.5);

    pdf.setFont('helvetica', 'normal');
    setColor(pdf, TEXT_SECONDARY, 'text');
    const names = r.defectCategories.slice(0, 2).map(d => clean(d.name)).join('  |  ');
    pdf.text(names, MARGIN + 72, y + 6.5, { maxWidth: CONTENT_W - 110 });

    setColor(pdf, TEXT_MUTED, 'text');
    pdf.text(r.date, PAGE_W - MARGIN - 2, y + 6.5, { align: 'right' });
    y += 10;
  });
}

// ─── PAGES 2–N: INDIVIDUAL REPORT ────────────────────────────────────────────
async function reportPage(pdf: jsPDF, report: Report) {
  pageHeader(pdf);
  pageFooter(pdf);

  const TOP = 12;

  // ── Report header bar ──
  filledRect(pdf, MARGIN, TOP, CONTENT_W, 14, LIGHT_GREY, BORDER);

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(10.5);
  setColor(pdf, NAVY, 'text');
  pdf.text(report.ref, MARGIN + 4, TOP + 6);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text(report.date, MARGIN + 4, TOP + 11);

  // Severity badge
  const sc = sevRgb(report.severity);
  filledRect(pdf, PAGE_W - MARGIN - 36, TOP + 3, 32, 8, sc);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(7);
  pdf.setTextColor(255, 255, 255);
  pdf.text(report.severity.toUpperCase() + ' RISK', PAGE_W - MARGIN - 20, TOP + 8.2, { align: 'center' });

  const COL_START = TOP + 17;
  const LEFT_X  = MARGIN;
  const LEFT_W  = 70;
  const RIGHT_X = MARGIN + LEFT_W + 5;
  const RIGHT_W = CONTENT_W - LEFT_W - 5;

  let leftY  = COL_START;
  let rightY = COL_START;

  // ── LEFT: Image ──
  const IMG_H = 62;
  if (report.previewUrl) {
    try {
      pdf.addImage(report.previewUrl, 'JPEG', LEFT_X, leftY, LEFT_W, IMG_H, undefined, 'MEDIUM');
      outlineRect(pdf, LEFT_X, leftY, LEFT_W, IMG_H);
    } catch {
      filledRect(pdf, LEFT_X, leftY, LEFT_W, IMG_H, [243, 244, 246] as [number,number,number]);
      pdf.setFontSize(7);
      setColor(pdf, TEXT_MUTED, 'text');
      pdf.text('Image unavailable', LEFT_X + LEFT_W / 2, leftY + IMG_H / 2, { align: 'center' });
    }
  } else {
    filledRect(pdf, LEFT_X, leftY, LEFT_W, IMG_H, [243, 244, 246] as [number,number,number]);
  }
  leftY += IMG_H + 2;

  // Analysis limitations banner
  if (report.analysisLimitations) {
    const limText = clean('Note: ' + report.analysisLimitations);
    const limLines = pdf.splitTextToSize(limText, LEFT_W - 4);
    const limH = limLines.length * 3.5 + 5;
    filledRect(pdf, LEFT_X, leftY, LEFT_W, limH, [245, 158, 11] as [number,number,number]);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(5.5);
    pdf.setTextColor(255, 255, 255);
    pdf.text(limLines, LEFT_X + 2, leftY + 4);
    leftY += limH + 3;
  } else {
    leftY += 2;
  }

  // ── LEFT: Defects Identified ──
  leftY = sectionLabel(pdf, 'Defects Identified', LEFT_X, leftY, LEFT_W);

  report.defectCategories.forEach((defect) => {
    const dc = sevRgb(defect.severity);
    const hasLong = !!defect.taxonomy_long;
    const chipH = hasLong ? 20 : 15;

    filledRect(pdf, LEFT_X, leftY, LEFT_W, chipH, LIGHT_GREY, BORDER);
    // Severity stripe
    setColor(pdf, dc, 'fill');
    pdf.rect(LEFT_X, leftY, 3, chipH, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    setColor(pdf, TEXT_PRIMARY, 'text');
    const nameLines = pdf.splitTextToSize(clean(defect.name), LEFT_W - 18);
    pdf.text(nameLines[0], LEFT_X + 5, leftY + 5.5);

    if (defect.taxonomy_short) {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(5.5);
      setColor(pdf, dc, 'text');
      pdf.text(clean(defect.taxonomy_short).toUpperCase(), LEFT_X + 5, leftY + 10);
    }

    if (defect.taxonomy_long && hasLong) {
      pdf.setFont('helvetica', 'italic');
      pdf.setFontSize(5.5);
      setColor(pdf, TEXT_MUTED, 'text');
      pdf.text(clean(defect.taxonomy_long), LEFT_X + 5, leftY + 15);
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    setColor(pdf, dc, 'text');
    pdf.text(`${defect.confidence}%`, LEFT_X + LEFT_W - 3, leftY + 5.5, { align: 'right' });

    leftY += chipH + 2;
  });

  // ── RIGHT: Urgency chip ──
  filledRect(pdf, RIGHT_X, rightY, RIGHT_W, 8, LIGHT_GREY, BORDER);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  setColor(pdf, TEXT_SECONDARY, 'text');
  pdf.text('Address: ' + clean(report.urgency), RIGHT_X + 4, rightY + 5.3);
  rightY += 11;

  // ── RIGHT: RICS Survey Notes ──
  rightY = sectionLabel(pdf, 'RICS Survey Notes', RIGHT_X, rightY, RIGHT_W);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  setColor(pdf, TEXT_PRIMARY, 'text');
  const survLines = pdf.splitTextToSize(clean(report.surveyDescription), RIGHT_W);
  pdf.text(survLines, RIGHT_X, rightY);
  rightY += survLines.length * 3.5 + 6;

  // ── RIGHT: Risk Matrix + Cost ──
  const halfW = (RIGHT_W - 3) / 2;

  filledRect(pdf, RIGHT_X, rightY, halfW, 24, LIGHT_GREY, BORDER);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text('RISK MATRIX', RIGHT_X + 3, rightY + 5);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  setColor(pdf, TEXT_PRIMARY, 'text');
  pdf.text('Likelihood: ' + clean(report.riskMatrix?.likelihood ?? 'N/A'), RIGHT_X + 3, rightY + 12);
  pdf.text('Impact:      ' + clean(report.riskMatrix?.impact ?? 'N/A'), RIGHT_X + 3, rightY + 19);

  const costX = RIGHT_X + halfW + 3;
  filledRect(pdf, costX, rightY, halfW, 24, LIGHT_GREY, BORDER);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text('INDICATIVE REPAIR COST', costX + 3, rightY + 5);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  setColor(pdf, TEXT_PRIMARY, 'text');
  if (report.costEstimate?.low != null) {
    pdf.text('Low:    GBP ' + report.costEstimate.low.toLocaleString(),  costX + 3, rightY + 12);
    pdf.text('Mid:    GBP ' + report.costEstimate.mid.toLocaleString(),  costX + 3, rightY + 17);
    pdf.text('High:  GBP ' + report.costEstimate.high.toLocaleString(), costX + 3, rightY + 22);
  } else {
    setColor(pdf, TEXT_MUTED, 'text');
    pdf.text('Insufficient data', costX + 3, rightY + 14);
  }
  rightY += 27;

  // ── RIGHT: Recommended Actions ──
  rightY = sectionLabel(pdf, 'Recommended Actions', RIGHT_X, rightY, RIGHT_W);

  report.recommendations.forEach((rec) => {
    const pc = rec.priority === 'P1' ? [220, 38, 38] as [number,number,number]
             : rec.priority === 'P2' ? [217, 119, 6] as [number,number,number]
             : [22, 163, 74] as [number,number,number];

    // P badge
    setColor(pdf, pc, 'fill');
    pdf.roundedRect(RIGHT_X, rightY, 9, 6.5, 1, 1, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(6);
    pdf.setTextColor(255, 255, 255);
    pdf.text(rec.priority, RIGHT_X + 4.5, rightY + 4.5, { align: 'center' });

    // Action
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7.5);
    setColor(pdf, TEXT_PRIMARY, 'text');
    const aLines = pdf.splitTextToSize(clean(rec.action), RIGHT_W - 13);
    pdf.text(aLines, RIGHT_X + 12, rightY + 4.5);
    rightY += aLines.length * 3.5 + 1;

    // Specialist · Timeframe
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    setColor(pdf, TEXT_MUTED, 'text');
    pdf.text(clean(rec.specialist) + '  |  ' + clean(rec.timeframe), RIGHT_X + 12, rightY + 1);
    rightY += 6.5;
  });

  rightY += 3;

  // ── RIGHT: Standards & References ──
  if (report.citations && report.citations.length > 0) {
    rightY = sectionLabel(pdf, 'Standards & References', RIGHT_X, rightY, RIGHT_W);

    report.citations.forEach((cite) => {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(7);
      setColor(pdf, NAVY, 'text');
      pdf.text(clean(cite.reference), RIGHT_X, rightY);
      rightY += 3.5;

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(6.5);
      setColor(pdf, TEXT_SECONDARY, 'text');
      const cLines = pdf.splitTextToSize(clean(cite.relevance), RIGHT_W);
      pdf.text(cLines, RIGHT_X, rightY);
      rightY += cLines.length * 3.2 + 3;
    });
  }
}

// ─── FINAL PAGE: PORTFOLIO SUMMARY ───────────────────────────────────────────
function portfolioPage(pdf: jsPDF, reports: Report[]) {
  pageHeader(pdf);
  pageFooter(pdf);

  let y = 16;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(15);
  setColor(pdf, NAVY, 'text');
  pdf.text('Portfolio Defect Intelligence', PAGE_W / 2, y, { align: 'center' });
  y += 5;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  setColor(pdf, TEXT_MUTED, 'text');
  pdf.text(`Comparing ${reports.length} surveyed ${reports.length === 1 ? 'property' : 'properties'}`, PAGE_W / 2, y, { align: 'center' });
  y += 10;

  // ── Severity Timeline ──
  y = sectionLabel(pdf, 'Severity Timeline', MARGIN, y, CONTENT_W);
  y += 1;

  const LABEL_W = 46;
  const BAR_W   = CONTENT_W - LABEL_W - 30;
  const TAG_X   = MARGIN + LABEL_W + BAR_W + 3;

  reports.forEach((r, i) => {
    const sc    = sevRgb(r.severity);
    const rowY  = y + i * 14;
    const score = Math.max((r.severityScore ?? 50) / 100, 0.06);

    // Short ref label
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    setColor(pdf, NAVY, 'text');
    // Show last segment of ref for brevity
    const shortRef = r.ref.split('-').slice(-1)[0] ?? r.ref;
    pdf.text(shortRef, MARGIN, rowY + 6);

    // Background track
    filledRect(pdf, MARGIN + LABEL_W, rowY, BAR_W, 9, [229, 231, 235] as [number,number,number]);

    // Filled portion
    filledRect(pdf, MARGIN + LABEL_W, rowY, Math.max(BAR_W * score, 5), 9, sc);

    // Score text on bar (white if bar is wide enough, else dark)
    const barFill = BAR_W * score;
    if (barFill > 18) {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(6);
      pdf.setTextColor(255, 255, 255);
      pdf.text(`${r.severityScore ?? '--'}`, MARGIN + LABEL_W + barFill - 3, rowY + 6, { align: 'right' });
    }

    // Severity label to right
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    setColor(pdf, sc, 'text');
    pdf.text(r.severity.toUpperCase(), TAG_X, rowY + 6);
  });

  y += reports.length * 14 + 8;

  // ── Defect Frequency Heatmap ──
  y = sectionLabel(pdf, 'Defect Frequency Heatmap', MARGIN, y, CONTENT_W);
  y += 2;

  // Collect all unique defect names in order
  const allDefects = Array.from(
    new Map(
      reports.flatMap(r => r.defectCategories.map(d => [d.name, d] as [string, DefectCategory]))
    ).values()
  );

  const NAME_W = 54;
  const DOT_AREA_W = CONTENT_W - NAME_W;
  const dotColW = DOT_AREA_W / reports.length;

  // Column headers (short ref IDs)
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6);
  setColor(pdf, NAVY, 'text');
  reports.forEach((r, i) => {
    const shortRef = r.ref.split('-').slice(-1)[0] ?? r.ref;
    const cx = MARGIN + NAME_W + i * dotColW + dotColW / 2;
    pdf.text(shortRef, cx, y, { align: 'center' });
  });
  y += 5;

  // Rows
  allDefects.forEach((defect, di) => {
    const rowY = y + di * 11;
    const bg = di % 2 === 0 ? LIGHT_GREY : ([255,255,255] as [number,number,number]);
    filledRect(pdf, MARGIN, rowY - 1, CONTENT_W, 11, bg);

    // Defect name
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    setColor(pdf, TEXT_PRIMARY, 'text');
    const nameClipped = pdf.splitTextToSize(clean(defect.name), NAME_W - 3)[0];
    pdf.text(nameClipped, MARGIN + 2, rowY + 6);

    // Dot per report column
    reports.forEach((r, ri) => {
      const match = r.defectCategories.find(d => d.name === defect.name);
      const cx = MARGIN + NAME_W + ri * dotColW + dotColW / 2;
      const cy = rowY + 4.5;

      if (match) {
        const dc = sevRgb(match.severity);
        setColor(pdf, dc, 'fill');
        pdf.ellipse(cx, cy, 4, 4, 'F');
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(5.5);
        pdf.setTextColor(255, 255, 255);
        pdf.text(`${match.confidence}`, cx, cy + 2, { align: 'center' });
      } else {
        setColor(pdf, [209, 213, 219] as [number,number,number], 'draw');
        pdf.setLineWidth(0.3);
        pdf.ellipse(cx, cy, 4, 4, 'S');
      }
    });
  });

  y += allDefects.length * 11 + 8;

  // ── Priority Action Summary ──
  y = sectionLabel(pdf, 'Priority Action Summary', MARGIN, y, CONTENT_W);
  y += 1;

  // Most common defect
  const freq: Record<string, number> = {};
  reports.forEach(r => r.defectCategories.forEach(d => { freq[d.name] = (freq[d.name] ?? 0) + 1; }));
  const topEntry = Object.entries(freq).sort((a, b) => b[1] - a[1])[0];

  const summary = topEntry
    ? `Across your portfolio, the most frequently observed defect is "${clean(topEntry[0])}", identified in ${topEntry[1]} of ${reports.length} ${reports.length === 1 ? 'property' : 'properties'}. The estimated combined remedial works budget across all properties ranges from GBP ${totalLow(reports).toLocaleString()} to GBP ${totalHigh(reports).toLocaleString()} (2025 UK market rates). It is strongly recommended that all Priority 1 actions are instructed without delay, and that a qualified RICS Chartered Surveyor is engaged to validate these findings prior to legal completion or any significant expenditure.`
    : 'No defects identified across portfolio.';

  filledRect(pdf, MARGIN, y, CONTENT_W, 32, LIGHT_GREY, BORDER);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  setColor(pdf, TEXT_PRIMARY, 'text');
  const sumLines = pdf.splitTextToSize(summary, CONTENT_W - 8);
  pdf.text(sumLines, MARGIN + 4, y + 7);
}

// ─── MAIN EXPORT ─────────────────────────────────────────────────────────────
export async function generatePDF(reports: Report[], context: SurveyContext): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const date = new Date().toLocaleString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });

  // Page 1: Cover
  coverPage(pdf, context, reports, date);

  // Pages 2–N: Individual reports
  for (const report of reports) {
    pdf.addPage();
    await reportPage(pdf, report);
  }

  // Final page: Portfolio
  pdf.addPage();
  portfolioPage(pdf, reports);

  pdf.save(`SurveyAI_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
}
