import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface DefectCategory {
  icon: string;
  name: string;
  taxonomy_short?: string;
  taxonomy_long?: string;
  confidence: number;
  severity: string;
}

interface Recommendation {
  priority: string;
  action: string;
  specialist: string;
  timeframe: string;
}

interface Citation {
  reference: string;
  title: string;
  relevance: string;
}

interface CostEstimate {
  low: number;
  mid: number;
  high: number;
}

interface Report {
  ref: string;
  date: string;
  previewUrl: string;
  severity: string;
  severityScore: number;
  urgency: string;
  defectCategories: DefectCategory[];
  surveyDescription: string;
  riskMatrix: { likelihood: string; impact: string };
  costEstimate: CostEstimate;
  recommendations: Recommendation[];
  citations: Citation[];
  analysisLimitations?: string;
}

interface SurveyContext {
  propertyType?: string;
  buildingAge?: string;
  locationType?: string;
  reportPurpose?: string;
}

const SEVERITY_COLORS: Record<string, string> = {
  Monitor:  '#2563eb',
  Low:      '#16a34a',
  Medium:   '#d97706',
  High:     '#ea580c',
  Critical: '#dc2626',
};

const NAVY = '#1a3a6b';
const GOLD = '#c9943a';
const LIGHT_GREY = '#f8f9fa';
const BORDER = '#e5e7eb';
const TEXT_PRIMARY = '#1a2035';
const TEXT_SECONDARY = '#4a5578';
const TEXT_MUTED = '#9ca3af';

// PDF dimensions (A4)
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 16;
const CONTENT_W = PAGE_W - MARGIN * 2;

function addPageHeader(pdf: jsPDF, pageNum: number, totalPages?: number) {
  // Top bar
  pdf.setFillColor(26, 58, 107);
  pdf.rect(0, 0, PAGE_W, 10, 'F');

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  pdf.text('SurveyAI', MARGIN, 6.5);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.text('Taurgo × Cardiff University · AI Hackathon 2026', PAGE_W / 2, 6.5, { align: 'center' });

  if (totalPages) {
    pdf.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, 6.5, { align: 'right' });
  }
}

function addPageFooter(pdf: jsPDF) {
  pdf.setDrawColor(229, 231, 235);
  pdf.setLineWidth(0.3);
  pdf.line(MARGIN, PAGE_H - 10, PAGE_W - MARGIN, PAGE_H - 10);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6.5);
  pdf.setTextColor(156, 163, 175);
  pdf.text(
    'Generated by SurveyAI · Powered by Claude AI (Anthropic) · For informational purposes only. Always consult a qualified RICS Chartered Surveyor.',
    PAGE_W / 2,
    PAGE_H - 6,
    { align: 'center', maxWidth: CONTENT_W }
  );
}

function drawSectionLabel(pdf: jsPDF, label: string, y: number): number {
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(7);
  pdf.setTextColor(26, 58, 107);
  pdf.text(label.toUpperCase(), MARGIN, y);

  pdf.setDrawColor(26, 58, 107);
  pdf.setLineWidth(0.3);
  pdf.line(MARGIN, y + 1, PAGE_W - MARGIN, y + 1);

  return y + 5;
}

function drawBox(pdf: jsPDF, x: number, y: number, w: number, h: number, fillHex?: string) {
  if (fillHex) {
    const r = parseInt(fillHex.slice(1, 3), 16);
    const g = parseInt(fillHex.slice(3, 5), 16);
    const b = parseInt(fillHex.slice(5, 7), 16);
    pdf.setFillColor(r, g, b);
    pdf.rect(x, y, w, h, 'F');
  }
  pdf.setDrawColor(229, 231, 235);
  pdf.setLineWidth(0.3);
  pdf.rect(x, y, w, h, 'S');
}

function wrapText(pdf: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight: number): number {
  const lines = pdf.splitTextToSize(text, maxWidth);
  pdf.text(lines, x, y);
  return y + lines.length * lineHeight;
}

// ─── PAGE: COVER ────────────────────────────────────────────────────────────
function addCoverPage(pdf: jsPDF, context: SurveyContext, reports: Report[], generatedDate: string) {
  addPageHeader(pdf, 1);

  let y = 24;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(26);
  pdf.setTextColor(26, 58, 107);
  pdf.text('SurveyAI', PAGE_W / 2, y, { align: 'center' });
  y += 9;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Property Defect Analysis Report', PAGE_W / 2, y, { align: 'center' });
  y += 6;

  pdf.setFontSize(8);
  pdf.setTextColor(156, 163, 175);
  pdf.text(`Generated: ${generatedDate}`, PAGE_W / 2, y, { align: 'center' });
  y += 12;

  // Divider
  pdf.setDrawColor(201, 148, 58);
  pdf.setLineWidth(0.8);
  pdf.line(MARGIN + 30, y, PAGE_W - MARGIN - 30, y);
  y += 10;

  // Survey Context Box
  y = drawSectionLabel(pdf, 'Survey Context', y);
  y += 2;

  const contextItems = [
    ['Property Type', context.propertyType || 'Not specified'],
    ['Building Age', context.buildingAge || 'Not specified'],
    ['Location Type', context.locationType || 'Not specified'],
    ['Report Purpose', context.reportPurpose || 'Not specified'],
  ];

  const colW = CONTENT_W / 2 - 3;
  contextItems.forEach(([label, value], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const bx = MARGIN + col * (colW + 6);
    const by = y + row * 16;

    drawBox(pdf, bx, by, colW, 13, '#f8f9fa');

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7);
    pdf.setTextColor(156, 163, 175);
    pdf.text(label.toUpperCase(), bx + 4, by + 5);

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(9);
    pdf.setTextColor(26, 58, 107);
    pdf.text(value, bx + 4, by + 10.5);
  });

  y += 36;

  // Portfolio Summary
  y = drawSectionLabel(pdf, 'Portfolio Summary', y);
  y += 2;

  // Stats row
  const statW = CONTENT_W / 3 - 2;
  const stats = [
    { label: 'Properties Analysed', value: String(reports.length) },
    { label: 'Highest Severity', value: getHighestSeverity(reports) },
    {
      label: 'Total Repair Budget',
      value: `£${getTotalBudgetLow(reports).toLocaleString()} – £${getTotalBudgetHigh(reports).toLocaleString()}`
    },
  ];

  stats.forEach((stat, i) => {
    const bx = MARGIN + i * (statW + 3);
    drawBox(pdf, bx, y, statW, 18, '#f8f9fa');

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    pdf.setTextColor(156, 163, 175);
    pdf.text(stat.label.toUpperCase(), bx + 4, y + 5.5);

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(11);
    const col = SEVERITY_COLORS[stat.label === 'Highest Severity' ? stat.value : 'Monitor'] || NAVY;
    const r = parseInt(col.slice(1,3),16), g = parseInt(col.slice(3,5),16), b = parseInt(col.slice(5,7),16);
    pdf.setTextColor(stat.label === 'Highest Severity' ? r : 26, stat.label === 'Highest Severity' ? g : 58, stat.label === 'Highest Severity' ? b : 107);
    pdf.text(stat.value, bx + 4, y + 14);
  });

  y += 24;

  // Property list
  y = drawSectionLabel(pdf, 'Reports Included', y);
  y += 2;

  reports.forEach((r, i) => {
    const severityColor = SEVERITY_COLORS[r.severity] || NAVY;
    const cr = parseInt(severityColor.slice(1,3),16);
    const cg = parseInt(severityColor.slice(3,5),16);
    const cb = parseInt(severityColor.slice(5,7),16);

    drawBox(pdf, MARGIN, y, CONTENT_W, 10, i % 2 === 0 ? '#f8f9fa' : '#ffffff');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(8);
    pdf.setTextColor(26, 58, 107);
    pdf.text(r.ref, MARGIN + 3, y + 6.5);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7.5);
    pdf.setTextColor(cr, cg, cb);
    pdf.text(r.severity.toUpperCase(), MARGIN + 45, y + 6.5);

    pdf.setTextColor(74, 85, 120);
    const defectNames = r.defectCategories.slice(0, 2).map(d => d.name).join(' · ');
    pdf.text(defectNames, MARGIN + 75, y + 6.5, { maxWidth: CONTENT_W - 115 });

    pdf.setTextColor(156, 163, 175);
    pdf.text(r.date, PAGE_W - MARGIN - 3, y + 6.5, { align: 'right' });

    y += 10;
  });

  addPageFooter(pdf);
}

// ─── PAGE: INDIVIDUAL REPORT ────────────────────────────────────────────────
async function addReportPage(
  pdf: jsPDF,
  report: Report,
  pageNum: number,
  context: SurveyContext
): Promise<void> {
  addPageHeader(pdf, pageNum);
  addPageFooter(pdf);

  let y = 14;

  // ── Report header ──
  pdf.setFillColor(248, 249, 250);
  pdf.rect(MARGIN, y, CONTENT_W, 14, 'F');
  pdf.setDrawColor(229, 231, 235);
  pdf.setLineWidth(0.3);
  pdf.rect(MARGIN, y, CONTENT_W, 14, 'S');

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(10);
  pdf.setTextColor(26, 58, 107);
  pdf.text(report.ref, MARGIN + 4, y + 5.5);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(156, 163, 175);
  pdf.text(report.date, MARGIN + 4, y + 11);

  // Severity badge
  const sevColor = SEVERITY_COLORS[report.severity] || NAVY;
  const sr = parseInt(sevColor.slice(1,3),16);
  const sg = parseInt(sevColor.slice(3,5),16);
  const sb = parseInt(sevColor.slice(5,7),16);

  pdf.setFillColor(sr, sg, sb);
  pdf.roundedRect(PAGE_W - MARGIN - 36, y + 3, 32, 8, 2, 2, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(7.5);
  pdf.setTextColor(255, 255, 255);
  pdf.text(`${report.severity.toUpperCase()} RISK`, PAGE_W - MARGIN - 20, y + 8.2, { align: 'center' });

  y += 17;

  // ── TWO COLUMN LAYOUT ──
  // Left col: image + defect chips
  // Right col: everything else
  const leftW = 74;
  const rightW = CONTENT_W - leftW - 4;
  const rightX = MARGIN + leftW + 4;

  // ── Image ──
  if (report.previewUrl) {
    try {
      const imgH = 56;
      pdf.addImage(report.previewUrl, 'JPEG', MARGIN, y, leftW, imgH, undefined, 'MEDIUM');
      pdf.setDrawColor(229, 231, 235);
      pdf.setLineWidth(0.3);
      pdf.rect(MARGIN, y, leftW, imgH, 'S');

      // Analysis limitations badge on image
      if (report.analysisLimitations) {
        pdf.setFillColor(245, 158, 11);
        pdf.rect(MARGIN, y + imgH - 8, leftW, 8, 'F');
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(5.5);
        pdf.setTextColor(255, 255, 255);
        const limText = pdf.splitTextToSize('⚠ ' + report.analysisLimitations, leftW - 4);
        pdf.text(limText[0], MARGIN + 2, y + imgH - 3.5);
      }
    } catch (e) {
      // Image failed to load — draw placeholder
      pdf.setFillColor(243, 244, 246);
      pdf.rect(MARGIN, y, leftW, 56, 'F');
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(156, 163, 175);
      pdf.text('Image', MARGIN + leftW / 2, y + 28, { align: 'center' });
    }
  }

  // ── Defect categories (below image) ──
  let leftY = y + 58;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  pdf.setTextColor(156, 163, 175);
  pdf.text('DEFECTS IDENTIFIED', MARGIN, leftY);
  leftY += 3;

  report.defectCategories.forEach((defect) => {
    const dc = SEVERITY_COLORS[defect.severity] || NAVY;
    const dr = parseInt(dc.slice(1,3),16);
    const dg = parseInt(dc.slice(3,5),16);
    const db = parseInt(dc.slice(5,7),16);

    drawBox(pdf, MARGIN, leftY, leftW, 14, '#f8f9fa');

    // Severity stripe on left
    pdf.setFillColor(dr, dg, db);
    pdf.rect(MARGIN, leftY, 2.5, 14, 'F');

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    pdf.setTextColor(26, 32, 53);
    const nameLines = pdf.splitTextToSize(defect.name, leftW - 14);
    pdf.text(nameLines[0], MARGIN + 5, leftY + 5);

    if (defect.taxonomy_short) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(5.5);
      pdf.setTextColor(dr, dg, db);
      pdf.text(defect.taxonomy_short.toUpperCase(), MARGIN + 5, leftY + 9.5);
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    pdf.setTextColor(dr, dg, db);
    pdf.text(`${defect.confidence}%`, MARGIN + leftW - 3, leftY + 5, { align: 'right' });

    leftY += 15;
  });

  // ── Right column content ──
  let rightY = y;

  // Urgency chip
  pdf.setFillColor(248, 249, 250);
  pdf.roundedRect(rightX, rightY, rightW, 8, 1.5, 1.5, 'F');
  pdf.setDrawColor(229, 231, 235);
  pdf.setLineWidth(0.2);
  pdf.roundedRect(rightX, rightY, rightW, 8, 1.5, 1.5, 'S');

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(74, 85, 120);
  pdf.text(`⏱  ${report.urgency}`, rightX + 4, rightY + 5.2);
  rightY += 11;

  // ── RICS Survey Notes ──
  rightY = drawSectionLabel(pdf, 'RICS Survey Notes', rightY);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  pdf.setTextColor(26, 32, 53);
  const surveyLines = pdf.splitTextToSize(report.surveyDescription, rightW);
  pdf.text(surveyLines, rightX, rightY);
  rightY += surveyLines.length * 3.5 + 5;

  // ── Risk + Cost side by side ──
  const halfW = (rightW - 3) / 2;

  // Risk Matrix
  drawBox(pdf, rightX, rightY, halfW, 22, '#f8f9fa');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  pdf.setTextColor(156, 163, 175);
  pdf.text('RISK MATRIX', rightX + 3, rightY + 5);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  pdf.setTextColor(26, 32, 53);
  pdf.text(`Likelihood: ${report.riskMatrix?.likelihood || '—'}`, rightX + 3, rightY + 11);
  pdf.text(`Impact: ${report.riskMatrix?.impact || '—'}`, rightX + 3, rightY + 17);

  // Cost Estimate
  const costX = rightX + halfW + 3;
  drawBox(pdf, costX, rightY, halfW, 22, '#f8f9fa');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6.5);
  pdf.setTextColor(156, 163, 175);
  pdf.text('INDICATIVE REPAIR COST', costX + 3, rightY + 5);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7);
  pdf.setTextColor(26, 32, 53);
  if (report.costEstimate?.low != null) {
    pdf.text(`Low:   £${report.costEstimate.low.toLocaleString()}`, costX + 3, rightY + 11);
    pdf.text(`Mid:    £${report.costEstimate.mid.toLocaleString()}`, costX + 3, rightY + 15.5);
    pdf.text(`High:  £${report.costEstimate.high.toLocaleString()}`, costX + 3, rightY + 20);
  } else {
    pdf.text('Insufficient data', costX + 3, rightY + 13);
  }

  rightY += 25;

  // ── Recommended Actions ──
  rightY = drawSectionLabel(pdf, 'Recommended Actions', rightY);

  report.recommendations.forEach((rec) => {
    const pColor = rec.priority === 'P1' ? '#dc2626' : rec.priority === 'P2' ? '#d97706' : '#16a34a';
    const pr = parseInt(pColor.slice(1,3),16);
    const pg = parseInt(pColor.slice(3,5),16);
    const pb = parseInt(pColor.slice(5,7),16);

    // Priority badge
    pdf.setFillColor(pr, pg, pb);
    pdf.roundedRect(rightX, rightY, 9, 6, 1, 1, 'F');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(6);
    pdf.setTextColor(255, 255, 255);
    pdf.text(rec.priority, rightX + 4.5, rightY + 4.2, { align: 'center' });

    // Action text
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7.5);
    pdf.setTextColor(26, 32, 53);
    const actionLines = pdf.splitTextToSize(rec.action, rightW - 13);
    pdf.text(actionLines, rightX + 12, rightY + 4.5);

    const actionH = actionLines.length * 3.5;
    rightY += actionH + 1;

    // Specialist + timeframe
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    pdf.setTextColor(156, 163, 175);
    pdf.text(`${rec.specialist}  ·  ${rec.timeframe}`, rightX + 12, rightY + 1);
    rightY += 5;
  });

  rightY += 2;

  // ── Standards & References ──
  if (report.citations && report.citations.length > 0) {
    rightY = drawSectionLabel(pdf, 'Standards & References', rightY);

    report.citations.forEach((cite) => {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(7);
      pdf.setTextColor(26, 58, 107);
      pdf.text(cite.reference, rightX, rightY);
      rightY += 3.5;

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(6.5);
      pdf.setTextColor(74, 85, 120);
      const citeLines = pdf.splitTextToSize(cite.relevance, rightW);
      pdf.text(citeLines, rightX, rightY);
      rightY += citeLines.length * 3 + 2;
    });
  }
}

// ─── PAGE: PORTFOLIO SUMMARY ─────────────────────────────────────────────────
function addPortfolioPage(pdf: jsPDF, reports: Report[], pageNum: number) {
  addPageHeader(pdf, pageNum);
  addPageFooter(pdf);

  let y = 16;

  // Title
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.setTextColor(26, 58, 107);
  pdf.text('Portfolio Defect Intelligence', PAGE_W / 2, y, { align: 'center' });
  y += 5;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(156, 163, 175);
  pdf.text(`Comparing ${reports.length} surveyed properties`, PAGE_W / 2, y, { align: 'center' });
  y += 10;

  // ── Severity Timeline ──
  y = drawSectionLabel(pdf, 'Severity Timeline', y);
  y += 2;

  const barMaxW = CONTENT_W - 70;

  reports.forEach((r, i) => {
    const sevColor = SEVERITY_COLORS[r.severity] || NAVY;
    const sr = parseInt(sevColor.slice(1,3),16);
    const sg = parseInt(sevColor.slice(3,5),16);
    const sb = parseInt(sevColor.slice(5,7),16);

    const fillPct = r.severityScore / 100;
    const rowY = y + i * 12;

    // Ref label
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7.5);
    pdf.setTextColor(26, 58, 107);
    pdf.text(r.ref, MARGIN, rowY + 5);

    // Background bar
    pdf.setFillColor(243, 244, 246);
    pdf.roundedRect(MARGIN + 42, rowY, barMaxW, 7, 1.5, 1.5, 'F');

    // Filled bar
    pdf.setFillColor(sr, sg, sb);
    pdf.roundedRect(MARGIN + 42, rowY, Math.max(barMaxW * fillPct, 6), 7, 1.5, 1.5, 'F');

    // Severity label
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    pdf.setTextColor(sr, sg, sb);
    pdf.text(r.severity.toUpperCase(), PAGE_W - MARGIN, rowY + 5, { align: 'right' });
  });

  y += reports.length * 12 + 8;

  // ── Defect Frequency Heatmap ──
  y = drawSectionLabel(pdf, 'Defect Frequency Heatmap', y);
  y += 3;

  // Build unique defect list
  const allDefects = Array.from(new Set(reports.flatMap(r => r.defectCategories.map(d => d.name))));
  const colW = Math.min(28, (CONTENT_W - 55) / reports.length);

  // Header row — report refs
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(6);
  pdf.setTextColor(26, 58, 107);
  reports.forEach((r, i) => {
    const shortRef = r.ref.split('-').pop() || r.ref;
    pdf.text(shortRef, MARGIN + 55 + i * colW + colW / 2, y, { align: 'center' });
  });
  y += 4;

  // Data rows
  allDefects.forEach((defectName, di) => {
    const rowY = y + di * 10;

    // Alternating row background
    if (di % 2 === 0) {
      pdf.setFillColor(248, 249, 250);
      pdf.rect(MARGIN, rowY - 1, CONTENT_W, 10, 'F');
    }

    // Defect name
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(6.5);
    pdf.setTextColor(26, 32, 53);
    const nameText = pdf.splitTextToSize(defectName, 50);
    pdf.text(nameText[0], MARGIN + 2, rowY + 5);

    // Confidence dots per report
    reports.forEach((r, ri) => {
      const match = r.defectCategories.find(d => d.name === defectName);
      const cx = MARGIN + 55 + ri * colW + colW / 2;
      const cy = rowY + 4.5;

      if (match) {
        const dc = SEVERITY_COLORS[match.severity] || NAVY;
        const dr = parseInt(dc.slice(1,3),16);
        const dg = parseInt(dc.slice(3,5),16);
        const db = parseInt(dc.slice(5,7),16);
        pdf.setFillColor(dr, dg, db);
        pdf.circle(cx, cy, 3, 'F');

        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(5.5);
        pdf.setTextColor(255, 255, 255);
        pdf.text(`${match.confidence}`, cx, cy + 1.5, { align: 'center' });
      } else {
        pdf.setDrawColor(229, 231, 235);
        pdf.setLineWidth(0.4);
        pdf.circle(cx, cy, 3, 'S');
      }
    });
  });

  y += allDefects.length * 10 + 8;

  // ── Priority Action Summary ──
  y = drawSectionLabel(pdf, 'Priority Action Summary', y);
  y += 3;

  // Find most common defect
  const defectCounts: Record<string, number> = {};
  reports.forEach(r => r.defectCategories.forEach(d => {
    defectCounts[d.name] = (defectCounts[d.name] || 0) + 1;
  }));
  const topDefect = Object.entries(defectCounts).sort((a, b) => b[1] - a[1])[0];

  const totalLow = getTotalBudgetLow(reports);
  const totalHigh = getTotalBudgetHigh(reports);

  const summaryText = topDefect
    ? `Across your portfolio, the most frequently observed defect is "${topDefect[0]}", appearing in ${topDefect[1]} of ${reports.length} properties. The estimated combined remedial works budget across all properties ranges from £${totalLow.toLocaleString()} to £${totalHigh.toLocaleString()} (2025 UK market rates). It is recommended that all Priority 1 actions are instructed without delay, and that a qualified RICS Chartered Surveyor is engaged to validate these findings prior to legal completion or significant expenditure.`
    : 'No defects identified across portfolio.';

  drawBox(pdf, MARGIN, y, CONTENT_W, 28, '#f8f9fa');
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(26, 32, 53);
  const summaryLines = pdf.splitTextToSize(summaryText, CONTENT_W - 8);
  pdf.text(summaryLines, MARGIN + 4, y + 7);
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function getHighestSeverity(reports: Report[]): string {
  const order = ['Critical', 'High', 'Medium', 'Low', 'Monitor'];
  for (const s of order) {
    if (reports.some(r => r.severity === s)) return s;
  }
  return 'Monitor';
}

function getTotalBudgetLow(reports: Report[]): number {
  return reports.reduce((sum, r) => sum + (r.costEstimate?.low || 0), 0);
}

function getTotalBudgetHigh(reports: Report[]): number {
  return reports.reduce((sum, r) => sum + (r.costEstimate?.high || 0), 0);
}

// ─── MAIN EXPORT ─────────────────────────────────────────────────────────────
export async function generatePDF(reports: Report[], context: SurveyContext): Promise<void> {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const generatedDate = new Date().toLocaleString('en-GB', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit'
  });

  const totalPages = 1 + reports.length + 1; // cover + reports + portfolio

  // Page 1: Cover
  addCoverPage(pdf, context, reports, generatedDate);

  // Pages 2–N: Individual reports
  for (let i = 0; i < reports.length; i++) {
    pdf.addPage();
    await addReportPage(pdf, reports[i], i + 2, context);
  }

  // Final page: Portfolio summary
  pdf.addPage();
  addPortfolioPage(pdf, reports, reports.length + 2);

  const filename = `SurveyAI_Report_${new Date().toISOString().slice(0,10)}.pdf`;
  pdf.save(filename);
}
